# Generated by Django 3.1 on 2020-10-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20201025_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
