# Generated by Django 3.1 on 2020-10-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20201025_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
