# Generated by Django 3.1 on 2020-11-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
